# ---- Actuator exposure ----
management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      probes:
        enabled: true          # exposes /actuator/health, /liveness, /readiness
      show-details: "when_authorized"   # or "never" if you prefer; avoid "always" in prod
      validate-group-membership: false  # Disable strict validation of group membership at startup. This prevents a hard failure
                                        # if the 'db' health contributor isn't registered early in the context lifecycle.

  # Explicitly enable the DB health contributor so readiness group can include it.
  health:
    db:
      enabled: true
    diskspace:
      enabled: true

# Define health groups explicitly so liveness does NOT hit DB, but readiness DOES.
management.endpoint.health.group:
  liveness:
    include: livenessState, diskSpace
  readiness:
    include: readinessState, db

# ---- DataSource & Hikari (keep Neon free to sleep) ----
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}           # set as Koyeb secret
    username: ${SPRING_DATASOURCE_USERNAME} # set as Koyeb secret
    password: ${SPRING_DATASOURCE_PASSWORD} # set as Koyeb secret
    hikari:
      minimum-idle: 0
      maximum-pool-size: 5
      idle-timeout: 120000        # 2 min; allows pool to drain so Neon can sleep
      connection-timeout: 10000
      max-lifetime: 1800000       # 30 min
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true     # if DB already has tables / older versions
    clean-disabled: true          # safety in prod

# ---- Additional settings ----
  jpa:
    hibernate:
      ddl-auto: validate          # validate schema on startup
logging:
  level:
    '[org.flywaydb]': DEBUG

# (show-details is set above under management.endpoint.health.show-details)
