# ---- Actuator exposure ----
management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      probes:
        enabled: true          # exposes /actuator/health, /liveness, /readiness
      show-details: "when_authorized"   # or "never" if you prefer; avoid "always" in prod
      validate-group-membership: false  # Disable strict validation of group membership at startup. This prevents a hard failure
                                        # if the 'db' health contributor isn't registered early in the context lifecycle.

  # Explicitly enable the DB health contributor so readiness group can include it.
  health:
    db:
      enabled: true
    diskspace:
      enabled: true

# Define health groups explicitly so liveness does NOT hit DB, but readiness DOES.
management.endpoint.health.group:
  liveness:
    include: livenessState, diskSpace
  readiness:
    include: readinessState, db

# ---- Spring Boot Startup ----
spring:
  main:
    lazy-initialization: false   # Allow normal initialization
  jpa:
    defer-datasource-initialization: true  # Defer JPA initialization until after Flyway completes
    hibernate:
      ddl-auto: validate          # validate schema on startup
  datasource:
    url: ${SPRING_DATASOURCE_URL}           # set as Koyeb/GitHub secret
    username: ${SPRING_DATASOURCE_USERNAME} # set as Koyeb secret
    password: ${SPRING_DATASOURCE_PASSWORD} # set as Koyeb secret
    hikari:
      minimum-idle: 0
      maximum-pool-size: 5
      idle-timeout: 120000        # 2 min; allows pool to drain so Neon can sleep
      connection-timeout: 30000   # 30 seconds (increased from 10s for Neon reliability)
      max-lifetime: 1800000       # 30 min
      connection-test-query: "SELECT 1"  # Validate connections with a test query
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: true
    out-of-order: true
    connect-retries: 10         # Retry connection 10 times
    connect-retries-interval: 5 # Wait 5 seconds between retries
    fail-on-missing-locations: false  # Don't fail if migration dirs don't exist

# ---- Additional settings ----
logging:
  level:
    '[org.flywaydb]': DEBUG

# (show-details is set above under management.endpoint.health.show-details)
