get:
  summary: Retrieve products with pagination
  description: |
    Returns paginated product list with metadata. Prevents loading entire table into memory.
    Default page size is 10 items. Includes total count and page information for client-side pagination controls.
  operationId: getPagedProducts
  tags:
    - Products
  security:
    - BearerAuth: []
  parameters:
    - name: page
      in: query
      required: false
      description: Zero-based page number (default 0)
      schema:
        type: integer
        minimum: 0
        default: 0
        example: 0
    - name: size
      in: query
      required: false
      description: Items per page (default 10, must be positive)
      schema:
        type: integer
        minimum: 1
        default: 10
        example: 10
  responses:
    '200':
      description: Paginated products returned successfully
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiResponsePaginated'
          example:
            success: true
            message: Paged products fetched successfully
            data:
              content:
                - id: 1
                  name: Laptop
                  quantity: 50
                  price: 999.99
                  totalValue: 49999.50
                - id: 2
                  name: Mouse
                  quantity: 200
                  price: 25.99
                  totalValue: 5198.00
              totalElements: 100
              totalPages: 10
              currentPage: 0
              pageSize: 10
    '400':
      description: Invalid parameters
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiResponseError'
    '401':
      description: Unauthorized - missing or invalid JWT token
