name: Keep Services Alive

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  ping-services:
    runs-on: ubuntu-latest

    steps:
      - name: Keep Backend Alive
        run: |
          curl -I https://stockease-0uii.onrender.com/api/health || echo "Backend is down"

      - name: Keep Frontend Alive
        run: |
          curl -I https://stockease-frontend.onrender.com || echo "Frontend is down"
